services:
  zabbix-agent2:
    image: zabbix/zabbix-agent2:alpine-7.2-latest
    container_name: zabbix-agent2
    env_file:
      - .env
    environment:
      ZBX_HOSTNAME: ""
      ZBX_SERVER_HOST: ${ZABBIX_SERVER_IP}
      ZBX_PASSIVE_ALLOW: "true"
      ZBX_ACTIVE_ALLOW: "true"
      ZBX_TLSCONNECT: "psk"
      ZBX_TLSACCEPT: "psk"
      ZBX_TLSPSKFILE: "/var/lib/zabbix/enc/zabbix-agent.psk"
      ZBX_TLSPSKIDENTITY: ${ZABBIX_AGENT_PSK_ID}
    ports:
      - "10050:10050"
    restart: unless-stopped
    privileged: true
    volumes:
      - ./psk:/var/lib/zabbix/enc:ro  
